In [2]:
import numpy as np

### multi-dimensional array

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim #dimension

2

In [ ]:
arr.shape # check row and colum using shape

(3, 3)

In [ ]:
arr.size #row x col

9

In [ ]:
arr.itemsize # size of elements in bytes

8

# 3. Array Reshaping- Reshape, Ravel and Flatten

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9]) # reshape
reshape = arr.reshape(3,3)
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # ravel for converting into 1D
ravel = arr.ravel()
ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ravel[0] = 100
print(arr)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [21]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # flatten for converting into 1D
flatten = arr.flatten()
flatten


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
flatten[0] = 100
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Arithmetic Operations on Array

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [9]:
print(a+b) #addition
print(a-b) #subtraction
print(a/b) #division
print(a*b) #multiplication
print(a//b) #integer division
print(a%b) #modulus
print(a**b) #power

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[0 0 0]
[1 2 3]
[  1  32 729]


### Universal Functions

In [13]:
arr = np.array([1,4,9,16])

In [14]:
#square root - sqrt()
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [19]:
#exponetional - exp() -e^x (x is any integer)
print(np.exp(7))

1096.6331584284585


In [20]:
#sine functions - sin
angles = ([0, np.pi, np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


# 4. Indexing and Slicing

In [ ]:
arr = ([2,4,6,8,10]) # Negative indexing
arr[-1:-4:-1]  # 10, 8, 4

[10, 8, 6]

In [ ]:
arr = ([2,4,6,8,10])
arr[::2]  #skip 1 value

[2, 6, 10]

In [30]:
arr = np.array([1,2,3,4,5,6,8,10])
arr[::-1] # reverse

array([10,  8,  6,  5,  4,  3,  2,  1])

In [33]:
arr = np.array([1,2,3,4,5,6,8,10])
arr[1::2] #odd index elements

array([ 2,  4,  6, 10])

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:1,0:3]) #[1,2,3]
print(matrix[1:3,1:3]) #[5 6] [8 9]

[[1 2 3]]
[[5 6]
 [8 9]]


In [39]:
#Built-in functions to perform indexing and slicing - take
arr = np.array([1,2,3,4,5,5,6])
idx = [0,2]
print(np.take(arr,idx))


[1 3]


# 5. Iterating with nditer()

In [40]:
arr = np.array([[1,2,3],[4,5,6]])

In [43]:
for x in np.nditer(arr):
    print(x,end=" ")

1 2 3 4 5 6 

In [45]:
#ndenumerate() - bth index + value

for idx,val in np.ndenumerate(arr):
    print(idx,val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# 6. Views Vs Copies

In [ ]:
arr = np.array([1,2,3,4,5,6])
view = arr[0:3] #create view
view

array([1, 2, 3])

In [ ]:
arr = np.array([1,2,3,4,5,6])
view = arr[0:3]
view[1]= 100 # modify view
print(view)
print(arr)

[  1 100   3]
[  1 100   3   4   5   6]


In [ ]:
copy = arr[0:3].copy() # cerate copy
print(copy)

[  1 100   3]


In [ ]:
copy[0] = 1000 #modify
print(copy) 
print(arr) #unchanged

[1000  100    3]
[  1 100   3   4   5   6]


In [ ]:
#Transpose of a matrix
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Transpose matrix")
print(np.transpose(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [64]:
### Swapaxes - swap 2 specific axes in a matrix
arr = np.array([[[1,2,3],[4,5,6]]])
np.shape(arr)

(1, 2, 3)

In [65]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 3)

In [67]:
print(arr)
print()
print(swap)

[[[1 2 3]
  [4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]


## Array Joining

In [74]:
#Concatenation
a = ([1,2,3])
b = ([5,6,7])

combine = np.concatenate((a,b))
print(combine)

[1 2 3 5 6 7]


In [ ]:
#Vertical stack
a = ([1,2,3])
b = ([5,6,7])

print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]]


In [77]:
#Vertical stack
a = ([1,2,3])
b = ([5,6,7])

print(np.hstack((a,b)))

[1 2 3 5 6 7]


In [84]:
#stack - ask for axis - 0 for row wise and 1 for column wise
a = ([1,2,3])
b = ([5,6,7])

print(np.stack((a,b), axis=0))

[[1 2 3]
 [5 6 7]]


## Array splitting

In [87]:
# splitting Arrays
arr1 = np.array([[1,2],[3,4],[5,6],[8,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 8]])

In [88]:
#split in 2 parts 
print(np.split(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [8, 8]])]


In [94]:
#vertical split
arr1 = np.array([[1,2],[3,4],[5,6],[8,8]])
print(np.hsplit(arr1,2))

[array([[1],
       [3],
       [5],
       [8]]), array([[2],
       [4],
       [6],
       [8]])]


In [96]:
#Horozontal split
arr1 = np.array([[1,2],[3,4],[5,6],[8,8]])
print(np.vsplit(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [8, 8]])]


In [ ]:
# Repeating- for repeating elements
arr = np.array([1,3,6,7])

print(np.repeat(arr,2))


[1 1 3 3 6 6 7 7]


In [99]:
# Tile - repeat whole array
arr = np.array([1,3,6,7])

print(np.tile(arr,2))


[1 3 6 7 1 3 6 7]


# 7. Aggregate Functions

In [102]:
arr = np.array([2,2,0,6,7])

print(np.sum(arr))        # sum of all elements
print(np.mean(arr))       # mean (average)
print(np.std(arr))        # standard deviation
print(np.min(arr))        # minimum element
print(np.max(arr))        # maximum element
print(np.median(arr))     # median value
print(np.var(arr))        # variance

print(np.prod(arr))       # product of all elements
print(np.ptp(arr))        # range (max - min)
print(np.percentile(arr,25))  # 25th percentile
print(np.percentile(arr,50))  # 50th percentile (same as median)
print(np.percentile(arr,75))  # 75th percentile
print(np.argmax(arr))     # index of maximum element
print(np.argmin(arr))     # index of minimum element

17
3.4
2.65329983228432
0
7
2.0
7.040000000000001
0
7
2.0
2.0
6.0
4
2


In [ ]:
#matrix sum cols wise
matrix = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
print(np.sum(matrix,axis = 1))

[ 6 15 24]


In [106]:
#matrix sum row wise
matrix = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
print(np.sum(matrix,axis = 0))



[12 15 18]


In [ ]:
# Cumulative Operations
arr = np.array([2,3,2,6,7])
print(np.cumprod(arr)) 
print(np.cumsum(arr))

[  2   6  12  72 504]
[ 2  5  7 13 20]


### Conditional based choices (Advanced Filtering)

In [108]:
#Where
arr = np.array([2,3,1,6,7])
res = np.where(arr < 3 , "Smaller", "Larger")
print(res)



['Smaller' 'Larger' 'Smaller' 'Larger' 'Larger']


In [109]:
#arg Where
arr = np.array([2,3,1,6,7])
res = np.argwhere(arr < 3)
print(res)



[[0]
 [2]]


In [ ]:
# Logical AND
arr = np.array([2,3,1,6,7])
temp = np.logical_and(arr > 3 , arr < 10)
print(temp)

[False False False  True  True]


In [112]:
# Logical OR
arr = np.array([2,3,1,6,7])
temp = np.logical_or(arr > 3 , arr < 10)
print(temp)

[ True  True  True  True  True]


In [113]:
matrix = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [117]:
#nonzero - return positions where array values are non zero
arr = np.array([2,3,0,0,7])
print(np.nonzero(arr))

(array([0, 1, 4]),)


# 8. Broadcasting

### 1. if shapes are equal, they are compatible
### 2. if one is 1, it can be stretched to match the other
### 3. if shapes are different and not 1 or equals - ERROR

In [119]:
image_arr = np.array([[200,300],[250,450]])
brightness = image_arr+20
brightness

array([[220, 320],
       [270, 470]])

In [120]:
#Vectorization
#np.vectorize()

def square(x):
    return x*x

vfunct = np.vectorize(square)

In [122]:
arr = np.array([2,3,0,0,7])
print(vfunct(arr))

[ 4  9  0  0 49]


# 9. Handle Missing Values/Null Values

In [124]:
#np.nan() - not a number
arr = np.array([2,3,4,5,np.nan,4])
arr

array([ 2.,  3.,  4.,  5., nan,  4.])

In [125]:
#np.inf and -np.inf -> positive and negative infinites
#isnan
#isinf
#isfinite

In [126]:
arr = np.array([2,3,4,5,np.nan,np.inf,10.3,4])
print(np.logical_or(np.isinf(arr) , np.isnan(arr)))

[False False False False  True  True False False]


In [ ]:
new_arr = np.nan_to_num(arr) # remove NAN/infinite number
new_arr

array([2.00000000e+000, 3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
       0.00000000e+000, 1.79769313e+308, 1.03000000e+001, 4.00000000e+000])