# Array Creation Functions

In [1]:
import numpy as np

In [2]:
#Creates an array filled with 0.
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#Creates an array filled with 1.
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Creates an array without initializing values.
arr1 = np.empty((2,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Creates an array filled with a specific value.
arr = np.full((2,3), 7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [8]:
#Creates numbers in a range with step.
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [10]:
#Creates numbers evenly spaced between two values.
arr = np.linspace(1,100,5)
print(arr)

[  1.    25.75  50.5   75.25 100.  ]


In [11]:
#Creates numbers evenly spaced on a logarithmic scale.
arr = np.logspace(1,3,3)
print(arr)

[  10.  100. 1000.]


In [17]:
#Creates an identity matrix.
arr = np.eye(4,3) #eye()
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [19]:
arr = np.identity(3) #identity()
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Random array generators

In [24]:
#Generates random numbers from a uniform distribution between 0 and 1.
#1D Array
print(np.random.rand(3))

[0.46909927 0.47522602 0.31604042]


In [25]:
#2D Array
print(np.random.rand(2,3))

[[0.4085934  0.73375718 0.88912924]
 [0.46935575 0.48484173 0.38452241]]


In [27]:
#Generates random numbers from a standard normal distribution (mean=0, std=1).
print(np.random.randn(4))

[-0.49769153 -0.32997998  1.29542539 -1.18963788]


In [28]:
#Generates random integers within a range.
#np.random.randint(low, high, size)
print(np.random.randint(1,10,5))

[8 2 4 4 9]


In [29]:
#Randomly selects elements from a given array.
arr = [10,20,30,40]
print(np.random.choice(arr))

10


In [32]:
#Sets the random seed for reproducibility.
np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [33]:
#shuffle array in place
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[5 3 1 2 4]


In [34]:
# random permutation
arr = np.array([1,2,3,4,5])
print(np.random.permutation(arr))

[3 4 5 1 2]


In [35]:
#Random floats in a range
arr = np.random.uniform(5,10,5)
print(arr)

[6.98383737 7.69408367 7.09597257 8.4260975  6.02226125]


In [36]:
#Random normal distribution with mean & std
arr = np.random.normal(50,10,5)
print(arr)

[41.40093393 67.72607629 38.89636945 51.81214267 55.64344866]


In [37]:
#Random sampling without replacement
arr = np.random.choice(10,5,replace=False)
print(arr)

[2 4 3 0 6]


# Array Joining (Combining Arrays)

In [38]:
#Joins arrays along an existing axis.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1,arr2))
print(result)

[1 2 3 4 5 6]


In [41]:
#Joins arrays along a new axis.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.stack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]


In [42]:
#Joins arrays column-wise.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]


In [43]:
#Joins arrays row-wise.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]


In [44]:
#Joins arrays along third axis (depth).
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(np.dstack((arr1,arr2)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Array Splitting

In [45]:
#Splits an array into equal parts.
arr = np.array([10,20,30,40,50,60])

result = np.split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [46]:
#Splits array even if equal division is not possible.
arr = np.array([10,20,30,40,50])

result = np.array_split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50])]


In [47]:
#Splits column-wise.
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(np.hsplit(arr,2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [48]:
#Splits row-wise.
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

print(np.vsplit(arr,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Sorting, Searching and Counting

In [ ]:
#Sorting
#Returns a sorted copy of the array.
arr = np.array([5,2,8,1,3])

print(np.sort(arr))

[1 2 3 5 8]


In [50]:
#Returns indices that would sort the array.
arr = np.array([50,10,40,20])

print(np.argsort(arr))

[1 3 2 0]


In [51]:
#Searching
#Returns indices where condition is True.
arr = np.array([10,15,20,25,30])

print(np.where(arr > 20))

(array([3, 4]),)


In [53]:
#Replace using where
arr = np.array([10,20,30,40])

result = np.where(arr>20,100,0)
print(result)

[  0   0 100 100]


In [54]:
#Finds index where element should be inserted to keep order.
arr = np.array([10,20,30,40])

print(np.searchsorted(arr,25))

2


In [55]:
#Counting
#Returns unique elements.
arr = np.array([1,2,2,3,3,3,4])

print(np.unique(arr))

[1 2 3 4]


In [56]:
#Count occurrences
arr = np.array([1,2,2,3,3,3,4])

values, counts = np.unique(arr, return_counts=True)

print(values)
print(counts)

[1 2 3 4]
[1 2 3 1]


In [57]:
#Counts non-zero elements.
arr = np.array([0,1,2,0,3,0,4])

print(np.count_nonzero(arr))

4


In [58]:
#Fancy Indexing
#Selecting elements using arrays.
arr = np.array([10,20,30,40])

print(arr[[0,2]])

[10 30]


In [59]:
#Boolean Masking (Advanced Filtering)
#Used heavily in data cleaning.
arr = np.array([10,20,30,40,50])
mask = arr > 25

print(arr[mask])

[30 40 50]


# Linear Algebra Module

In [ ]:
#Matrix Multiplication
#Use np.matmul() or @ operator.
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.matmul(A,B))
#print(A @ B)

[[19 22]
 [43 50]]


In [61]:
#Vector Dot Product
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


In [62]:
#Determinant
#Use np.linalg.det().
A = np.array([[1,2],
              [3,4]])

print(np.linalg.det(A))

-2.0000000000000004


In [63]:
#Matrix Inverse
#Use np.linalg.inv().
A = np.array([[1,2],
              [3,4]])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [64]:
#Eigenvalues and Eigenvectors
#Use np.linalg.eig().
A = np.array([[4,2],
              [1,3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [65]:
#Limits values within a specified range.
arr = np.array([1,5,10,15,20])

print(np.clip(arr,5,15))

[ 5  5 10 15 15]


In [66]:
#Computes the vector or matrix norm (magnitude).
arr = np.array([3,4])

print(np.linalg.norm(arr))

5.0


In [67]:
#Computes the covariance matrix.
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

print(np.cov(x,y))

[[1.66666667 3.33333333]
 [3.33333333 6.66666667]]


In [68]:
# Computes the correlation coefficient matrix.
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


In [69]:
#Computes numerical gradient of an array.
arr = np.array([1,3,7,15])

print(np.gradient(arr))

[2. 3. 6. 8.]


# File Input / Output Saving and loading arrays.

In [71]:
#Saves a single NumPy array in binary format.
arr = np.array([10,20,30,40])

np.save("data.npy", arr)

In [72]:
#Loads a saved NumPy array.
data = np.load("data.npy")

print(data)

[10 20 30 40]


In [73]:
#Used when saving multiple arrays in one file.
a = np.array([1,2,3])
b = np.array([4,5,6])

np.savez("arrays.npz", arr1=a, arr2=b)

In [74]:
#Load .npz file
data = np.load("arrays.npz")

print(data["arr1"])
print(data["arr2"])

[1 2 3]
[4 5 6]


In [75]:
#Saves array in human-readable text format.
arr = np.array([10,20,30])

np.savetxt("data.txt", arr)

In [76]:
#np.loadtxt() — Load text file
data = np.loadtxt("data.txt")

print(data)

[10. 20. 30.]


# Performance vs Python Loops

In [77]:
arr = list(range(1000000))

result = [x*2 for x in arr]


In [78]:
arr = np.arange(1000000)

result = arr * 2