In [57]:
import numpy as np   #np is alias

## 1.Numpy Arrays

In [58]:
range = np.arange(1,10,2) # start stop and step
range

array([1, 3, 5, 7, 9])

### linspace evenly space number

In [59]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# logSpace

In [60]:
log_arr = np.logspace(1,3,3)
log_arr

array([  10.,  100., 1000.])

### array of zeros

In [61]:
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

In [62]:
arr_zero_2d = np.zeros([4,3])
arr_zero_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### array of one

In [63]:
arr_one = np.ones([2,4], dtype=int)
arr_one

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### array of any values

In [64]:
arr_value = np.full(10,2)
arr_value

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
arr_value = np.full([2,2],2)  # row , col , value
arr_value

array([[2, 2],
       [2, 2]])

### uninitialized array

In [66]:
arr_uni = np.empty([2,3])
arr_uni

array([[9.9e-324, 1.5e-323, 2.0e-323],
       [9.9e-324, 1.5e-323, 2.0e-323]])

### random float values

In [67]:
arr = np.random.rand(5)
arr

array([0.02167555, 0.31525242, 0.85636809, 0.49461358, 0.59876003])

In [68]:
arr = np.random.randn(3)  # standard normal distribution
arr

array([-0.60771459,  0.02611936, -0.46873903])

### random randint

In [69]:
arr = np.random.randint(10,100, size = (3,3))  # start ,stop , size
arr

array([[32, 60, 25],
       [51, 10, 59],
       [20, 97, 91]], dtype=int32)

## 2.Numpy Data Types and Type Casting

In [70]:
arr = np.array([2,3,4,2,3,4])
arr

array([2, 3, 4, 2, 3, 4])

In [71]:
arr = np.array([2,3,4,2.2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [72]:
lst = ["string",3,2,1]
print(type(lst))
arr = np.array(lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [73]:
arr = np.array([4,3,2,4])
arr.dtype

dtype('int64')

### int to float and viceversa

In [74]:
arr = np.array([4,3,2,4],dtype=float)
arr.dtype

dtype('float64')

In [75]:
arr = np.array([1,2,3])
new_arr = arr.astype(np.float64)
new_arr.dtype

dtype('float64')

### Type Casting Errors

In [ ]:
arr = np.array(["1","2","Raj"])  #Invalid Literal Error
new_arr = arr.astype(np.int64)
new_arr.dtype

ValueError: invalid literal for int() with base 10: np.str_('Raj')

In [ ]:
a = np.array([200], dtype=np.int8)  #Overflow Error

NameError: name 'np' is not defined

In [2]:
a = np.array([1.9999])  #Precision Loss
b = a.astype(int)

print(b)  # 1

NameError: name 'np' is not defined

In [3]:
a = np.array([1+2j])  #Complex to Float Error
a.astype(float)

NameError: name 'np' is not defined