In [ ]:
import pandas as pd #alias

In [ ]:
s = pd.Series([20,30,40,10,50])
s

0    20
1    30
2    40
3    10
4    50
dtype: int64

In [ ]:
s.name = "Calories"

# 1.Inspection / Information Methods

In [ ]:
print(s.head())        # First 5 values
print(s.tail())        # Last 5 values
print(s.info())        # Summary info
print(s.describe())    # Statistical summary
print(s.dtype)         # Data type
print(s.shape)         # Size of Series
print(s.size)          # Number of elements
print(s.index)         # Index labels
print(s.values)        # Underlying NumPy array

0    20
1    30
2    40
3    10
Name: numbers, dtype: int64
0    20
1    30
2    40
3    10
Name: numbers, dtype: int64
<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: numbers
Non-Null Count  Dtype
--------------  -----
4 non-null      int64
dtypes: int64(1)
memory usage: 164.0 bytes
None
count     4.000000
mean     25.000000
std      12.909944
min      10.000000
25%      17.500000
50%      25.000000
75%      32.500000
max      40.000000
Name: numbers, dtype: float64
int64
(4,)
4
RangeIndex(start=0, stop=4, step=1)
[20 30 40 10]


# 2. Statistical / Aggregation Methods

In [ ]:
print(s.sum())      # Sum of values
print(s.mean())     # Average
print(s.median())   # Median
print(s.min())      # Minimum
print(s.max())      # Maximum
print(s.std())      # Standard deviation
print(s.var())      # Variance
print(s.count())    # Non-null values

100
25.0
25.0
10
40
12.909944487358056
166.66666666666666
4


# 3. Sorting Methods

In [ ]:
print(s.sort_values())   # Sort values
print(s.sort_index())    # Sort by index

3    10
0    20
1    30
2    40
Name: numbers, dtype: int64
0    20
1    30
2    40
3    10
Name: numbers, dtype: int64


# 4. Indexing / Selection Methods

In [ ]:
# Methods based indexing
print(s.loc[1])   # Access by label
print(s.iloc[1])  # Access by position
print(s.at[1])    # Fast label access
print(s.iat[1])   # Fast integer access

30
30
30
30


In [ ]:
#Indexing
print(s[0])


20


In [ ]:
print(s[1:3])

1    30
2    40
Name: numbers, dtype: int64


In [ ]:
s[2:4]

2    40
3    10
Name: numbers, dtype: int64

# 5. Value Counting & Unique

In [ ]:
print(s.value_counts())   # Frequency
print(s.unique())         # Unique values
print(s.nunique())        # Count unique

numbers
20    1
30    1
40    1
10    1
Name: count, dtype: int64
[20 30 40 10]
4


# 6. Transformation Methods

In [ ]:
print(s.apply(lambda x: x*2))   # Apply function
print(s.map(lambda x: x+5))     # Element mapping
print(s.astype(float))          # Change datatype

0    40
1    60
2    80
3    20
Name: numbers, dtype: int64
0    25
1    35
2    45
3    15
Name: numbers, dtype: int64
0    20.0
1    30.0
2    40.0
3    10.0
Name: numbers, dtype: float64


# 

# 7. Missing Value Handling

In [ ]:
print(s.isna())      # Detect NaN
print(s.notna())     # Non-null check
print(s.dropna())    # Remove missing
print(s.fillna(0))   # Replace NaN

0    False
1    False
2    False
3    False
Name: numbers, dtype: bool
0    True
1    True
2    True
3    True
Name: numbers, dtype: bool
0    20
1    30
2    40
3    10
Name: numbers, dtype: int64
0    20
1    30
2    40
3    10
Name: numbers, dtype: int64


#  8. Mathematical Operations

In [ ]:
print(s + 10)  #add
print(s * 2)   #multiply
print(s ** 2)  #power

0    30
1    40
2    50
3    20
Name: numbers, dtype: int64
0    40
1    60
2    80
3    20
Name: numbers, dtype: int64
0     400
1     900
2    1600
3     100
Name: numbers, dtype: int64


# 9. Conversion Methods

In [ ]:
print(s.to_list())    # Convert to list
print(s.to_numpy())   # Convert to NumPy
print(s.to_dict())    # Convert to dictionary

[20, 30, 40, 10]
[20 30 40 10]
{0: 20, 1: 30, 2: 40, 3: 10}


# 10. Index Operations

In [ ]:
print(s.reset_index())   # Reset index
print(s.rename("scores")) # Rename series

    index   0
0   apple  20
1  grapes  30
2  banana  40
3   guava  10
4  papaya  50
apple     20
grapes    30
banana    40
guava     10
papaya    50
Name: scores, dtype: int64


In [ ]:
s.name

'Calories'

In [ ]:
index = ["apple", "grapes", "banana","guava", "papaya"]

In [ ]:
s.index = index
s

apple     20
grapes    30
banana    40
guava     10
papaya    50
Name: Calories, dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
print(s.iloc[1]) #working
# s.iloc['grapes'] # not working bcoz this is not a lcation anymore
print(s.loc['grapes'])

30
30


In [ ]:
#start and stop values included in 'loc'
s.loc['grapes':'guava']

grapes    30
banana    40
guava     10
Name: Calories, dtype: int64

In [ ]:
fruits_protein = {
    "Apple": 0.3,
    "Banana": 1.3,
    "Orange": 0.9,
    "Guava": 2.6,
    "Mango": 0.8,
    "Papaya": 0.5,
    "Pomegranate": 1.7,
    "Strawberry": 0.7
}


In [ ]:
s2 = pd.Series(fruits_protein)
s2

Apple          0.3
Banana         1.3
Orange         0.9
Guava          2.6
Mango          0.8
Papaya         0.5
Pomegranate    1.7
Strawberry     0.7
dtype: float64

In [ ]:
s2.name = "Protein"

In [ ]:
s2.name

'Protein'

## Conditional Selection

In [ ]:
s2>1  #protein greater than 1 -> True

Apple          False
Banana          True
Orange         False
Guava           True
Mango          False
Papaya         False
Pomegranate     True
Strawberry     False
Name: Protein, dtype: bool

In [ ]:
#now i want to print only those fruits which have protein greater than 1
s2[s2>1]

Banana         1.3
Guava          2.6
Pomegranate    1.7
Name: Protein, dtype: float64

## Logical Operator

In [ ]:
#And , Or , Not
#AND
s2[(s2 > 0.5) & (s2 < 1)]

Orange        0.9
Mango         0.8
Strawberry    0.7
Name: Protein, dtype: float64

In [ ]:
#OR
s2[(s2 == 0.7 ) | (s2 == 0.9)]

Orange        0.9
Strawberry    0.7
Name: Protein, dtype: float64

In [ ]:
#NOT
s2[~(s2 == 0.7)]

Apple          0.3
Banana         1.3
Orange         0.9
Guava          2.6
Mango          0.8
Papaya         0.5
Pomegranate    1.7
Name: Protein, dtype: float64

## Modifying

In [ ]:
s2["guava"] = 10
s2

Apple           0.3
Banana          1.3
Orange          0.9
Guava           2.6
Mango           0.8
Papaya          0.5
Pomegranate     1.7
Strawberry      0.7
guava          10.0
Name: Protein, dtype: float64

# QUERIES

In [ ]:
import numpy as np

In [ ]:
s = pd.Series(['a',np.nan,1,np.nan,2])
s.notnull().sum()


#OUTPUT ...?

np.int64(3)

In [ ]:
#EXPLAINATION
# ans-3 becoz when you do "s.notnull()" is will give you true or false values 
# and there are 3 true values including 'a', 1, 2 ad hence the sum() count the true values and give 3 as ANS


In [ ]:
s.notnull()

NameError: name 's' is not defined